services:
  users:
    build:
      context: ./users
    platform: linux/amd64
    ports: ["3001:3000"]

  posts:
    build:
      context: ./posts
    platform: linux/amd64
    ports: ["3002:3000"]

  threads:
    build:
      context: ./threads
    platform: linux/amd64
    ports: ["3003:3000"]
